name: CI Ubuntu Jammy (Devcontainer)

on:
  repository_dispatch:
    types:
    - build-jammy
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [jammy, noble]
    steps:
    - name: Maximize build space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pre-build dev container image
      if: github.ref == 'refs/heads/main' && github.repository == 'mc-rtc/mc-rtc-superbuild'
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/mc-rtc/mc-rtc-superbuild
        imageTag: ${{ matrix.os }}
        subFolder: .github/devcontainer/${{ matrix.os }}
        configFile: .github/devcontainer/${{ matrix.os }}/devcontainer.json
        cacheFrom: ghcr.io/arntanguy/mc-rtc-superbuild
        push: always
